version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements/ci.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Configure VIS PyPi Repository
          command: |
            mkdir -p ~/.config/pip/
            echo -e "[global]" >> ~/.config/pip/pip.conf
            echo -e "extra-index-url = ${VIS_PYPI_URL}" >> ~/.config/pip/pip.conf
            echo -e "trusted-host = pypi.api.vet"
      - run:
          name: Install Requirements
          command: |
            python -m venv ../venv
            . ../venv/bin/activate
            pip install --trusted-host pypi.api.vet -r requirements/ci.txt
      - save_cache:
          paths:
            - ../venv
          key: v1-dependencies-{{ checksum "requirements/ci.txt" }}
      - run:
          name: Python Version
          command: python -V
      - run:
          name: Tests
          when: always
          command: |
            . ../venv/bin/activate
            python -m pytest \
              --pylama --bandit \
              --junitxml=../tests_results/junit.xml \
              --cov=. --cov-report=xml:../tests_artifacts/coverage.xml --cov-report=html:../tests_artifacts/coverage/ \
              datagrinder/
      - store_test_results:
          path: ../tests_results/
      - store_artifacts:
          path: ../tests_artifacts/


orbs:
  jira: circleci/jira@1.0.5


workflows:
  version: 2.1

  datagrinder:
    jobs:
      - test:
          post-steps:
            - jira/notify
